### ISSUE TITLE
Integrate firebase/firestore (Test package dependencies managers)

### ISSUE THREAD

**Issue by yura-hb** [Daniil2000/Coffee-App#1]
Reference: 

1.  Learn docs side https://firebase.google.com/docs/firestore
2. Investigate firestore library https://github.com/firebase/firebase-ios-sdk

Goal:

1. Integrate firebase via cocoa pods via terminal (Testing)
2. Integrate firebase via Carthage (Testing)
3. Try integrate with SPM

**Comment by Daniil2000** [comment]
Have forgotten to create a new branch before made a new commit. However, managed to integrate firebase into Coffee App.

**Comment by yura-hb** [comment]
Please move back the head commit before and create separate branches for carthage/spm. After that compare build times for each branch, there is an important thing there

**Comment by Daniil2000** [comment]
Carthage dependency manager provides the quickest build time

**Comment by yura-hb** [comment]
Yes, the Carthage package manager pre-builds libraries before adding them to the project. That's why you don't need to rebuild Firestore code every time and so you have time boost. You can select the type you want to continue to work with and merge it in the master project and I will close the issue
